on:
  push:
    branches:
      - master

  name: FTP Deployer
  uses: sand4rt/ftp-deployer@v1.7
  with:
    sftp: false # optional
    host: ftp://top2tenasia.xyz # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
    port: 21 # optional, default is: 21
    username: u126433241 # FTP username
    password: Top2TenAsia2020 # FTP password
    remote_folder: ${{ secrets.FTP_REMOTE_FOLDER }} # optional, remote path of your FTP server
    local_folder: dist # optional, local path, default is: dist
    cleanup: false # optional, remove existing files inside FTP remote folder
    include: '[]' # optional, e.g. '['dist']'
    exclude: '[]' # optional, e.g. '['node_modules/**', '.git/**', '*.env']'
    passive: true # optional