on:
  push:
    branches:
      - main

  name: FTP Deployer
  uses: sand4rt/ftp-deployer@v1.7
  with:
    sftp: false # optional
    host: ftp://top2tenasia.xyz # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
    port: 21 # optional, default is: 21
    username: ${{ secrets.FTP_USERNAME }} # FTP username
    password: ${{ secrets.FTP_PASSWORD }} # FTP password
